language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g bower
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - gulp --node-server --mock-backend & # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
script:
  - gulp test-for-ci
  - gulp send-stats-to-coveralls
  - npm run protractor
addons:
  sauce_connect: true
